version: '3.1'
services:
  syncthing:
    build: 
        context: .
    restart: always
    container_name: syncthing
    ports:
      - 0.0.0.0:8384:8384
      - 22000:22000
      - 21027:21027
    volumes:
      # Adjust to your needs
       - /mnt/hdd1/syncthing_data:/var/syncthing
