version: '3.1'
services:
  syncthing:
    build: 
        context: .
    # use image instead of build if you don't want to build the image by yourself
    #image: neilschark/syncthing-arm:latest
    restart: always
    container_name: syncthing
    # Use network_mode or ports. See Docker reference for difference. 'host' is needed for local discovery.
    network_mode: 'host'
    #ports:
    #  - 0.0.0.0:8384:8384
    #  - 22000:22000
    #  - 21027:21027
    volumes:
      # Adjust to your needs
       - /mnt/hdd1/syncthing_data:/var/syncthing
